### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by starlightknown** [Agrover112/Graduate_Admissions_Prediction#7]
add contributing file for new contributors to contribute to your project

**Comment by slayer321** [comment]
Hey, @starlightknown  I'm new to open source and will like to contribute to this project. can you guide me on what needs to be done?

**Comment by Agrover112** [comment]
> Hey, @starlightknown I'm new to open source and will like to contribute to this project. can you guide me on what needs to be done?

Hey @slayer321  good to have you here. 
You can look at example templates from CONTRIBUTING.md online . Fork the repo, add the CONTRIBUTING.md file, raise a PR , I will them review and accept your PR. If accepted you get your green square! (i.e your changes are accepted ) Hope this helps!

**Comment by slayer321** [comment]
Understood, working on it.
